### ISSUE TITLE
NoMethodError thrown while logging in using Test Authenticator

### ISSUE THREAD

**Issue by ghost** [rubycas/rubycas-server#17]
Working from the head release at github, on Mac OS X, I did the following:
1. Uninstalled all rubycas-server gems
2. Run rubycas-server/bin/rubycas-server
3. Set the config.yml file it generated to use the CASServer::Authenticators::Test
4. Run rubycas-server again
5. Attempt to login using username = test, password = testpassword

Expected: Login to work
Actual: Received the following exception -

```
NoMethodError: undefined method `merge' for nil:NilClass
    /Users/myusername/projects/rubycas-server/lib/casserver/controllers.rb:136:in 'post'
    /Users/myusername/projects/rubycas-server/lib/casserver/controllers.rb:133:in 'each'
    /Users/myusername/projects/rubycas-server/lib/casserver/controllers.rb:133:in `post'
```

Looking at the code it appears as though this may be related to the changes that make Authenciators configure on every request. The same config.yml file works fine with the last known gem (gunark-rubycas-server-0.8.0.20090812) which predates the Authentication changes I believe.

For reference, here is the entire config.yml file.

```
server: webrick
port: 443
ssl_cert: /Users/myusername/projects/rubycas-server/demo.pem

database:
  adapter: mysql
  database: casserver
  username: root
  password: 
  host: localhost

authenticator:
  class: CASServer::Authenticators::Test

theme: simple
organization: CAS
infoline: 
default_locale: en

log:
  file: /var/log/casserver.log
  level: INFO
```
